export const TABLES = {
  USERS: 'karuna_users',
  REFRESH_TOKENS: 'karuna_refresh_tokens',
  CATEGORIES: 'karuna_categories',
  ITEMS: 'karuna_items',
  SALES: 'karuna_sales',
  SALE_ITEMS: 'karuna_sale_items',
  CUSTOMERS: 'karuna_customers',
  STOCK_MUTATIONS: 'karuna_stock_mutations',
  SUPPLIERS: 'karuna_suppliers',
  PURCHASES: 'karuna_purchases',
  PURCHASE_ITEMS: 'karuna_purchase_items',
  PRICE_HISTORIES: 'karuna_price_histories',
  SUPPLIER_DEBT_PAYMENTS: 'karuna_supplier_debt_payments',
  RETURNS: 'karuna_returns',
  STOCK_OPNAMES: 'karuna_stock_opnames',
  CUSTOMER_DEBT_PAYMENTS: 'karuna_customer_debt_payments',
  EXPENSE_CATEGORIES: 'karuna_expense_categories',
  EXPENSES: 'karuna_expenses',
  INVESTORS: 'karuna_investors',
  JOURNALS: 'karuna_journals',
} as const;
